name: Build Lambda Functions
description: Compile Go Lambda functions and upload build artifacts

inputs:
  lambda-build-dir:
    description: Directory for Lambda build artifacts
    required: true
  upload-lambda-artifact:
    description: Whether to upload or not the lambda artifact
    required: false
    default: 'false'
  lambda-artifact-name:
    description: Name for Lambda artifact

outputs:
  build-outcome:
    description: Build step outcome
    value: ${{ steps.build.outcome }}

runs:
  using: composite
  steps:
    - name: Validate Lambda Artifact Name is Required
      if: ${{ inputs.upload-lambda-artifact == 'true' && inputs.lambda-artifact-name == '' }}
      shell: bash
      run: |
        echo "::error::lambda-artifact-name input is required when upload-lambda-artifact is set to true"
        exit 1

    - name: Build Lambda Functions
      id: build
      shell: bash
      run: |
        chmod +x "$BUILD_SCRIPT"
        "$BUILD_SCRIPT"
      env:
        BUILD_SCRIPT: ${{ github.workspace }}/.github/scripts/build-lambda.sh
        BUILD_DIR: ${{ inputs.lambda-build-dir }}

    - name: Upload Lambda Build Artifacts
      if: ${{ inputs.upload-lambda-artifact == 'true' }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.lambda-artifact-name }}
        path: ${{ inputs.lambda-build-dir }}
        if-no-files-found: error
        overwrite: true
        retention-days: 5