init-prod:
	cd environments/prod && terraform init -backend-config="../../state.config"

plan-prod:
	cd environments/prod && terraform plan

apply-prod:
	cd environments/prod && terraform apply

destroy-prod:
	cd environments/prod && terraform destroy