name: Terraform Plan
description: Generate and optionally upload Terraform plan with detailed exit code

inputs:
  upload-plan-artifact:
    description: Whether to upload or not the plan artifact
    required: false
    default: 'false'
  tfplan-binary:
    description: Name of Terraform plan binary file
    required: true
  var-file:
    description: Path to Terraform variables file
    required: true

outputs:
  plan-exitcode:
    description: Terraform plan exit code
    value: ${{ steps.plan.outputs.exitcode }}
  plan-outcome:
    description: Plan step outcome
    value: ${{ steps.plan.outcome }}

runs:
  using: composite
  steps:
    - name: Plan Terraform
      id: plan
      shell: bash
      run: |
        set +e
        terraform plan \
          -var-file="${{ inputs.var-file }}" \
          -out="${{ inputs.tfplan-binary }}" \
          -detailed-exitcode \
          -no-color \
          -input=false

        TF_EXITCODE=$?
        set -e

        [[ $TF_EXITCODE -ne 1 ]] || exit 1
        echo "exitcode=$TF_EXITCODE" >> $GITHUB_OUTPUT
      working-directory: terraform/

    - name: Upload Plan Artifact
      if: ${{ inputs.upload-plan-artifact == 'true' }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.tfplan-binary }}
        path: terraform/${{ inputs.tfplan-binary }}
        if-no-files-found: error
        overwrite: true
        retention-days: 5
